//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace ShippingManager
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Shipping_ManagerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Shipping_ManagerEntities object using the connection string found in the 'Shipping_ManagerEntities' section of the application configuration file.
        /// </summary>
        public Shipping_ManagerEntities() : base("name=Shipping_ManagerEntities", "Shipping_ManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Shipping_ManagerEntities object.
        /// </summary>
        public Shipping_ManagerEntities(string connectionString) : base(connectionString, "Shipping_ManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Shipping_ManagerEntities object.
        /// </summary>
        public Shipping_ManagerEntities(EntityConnection connection) : base(connection, "Shipping_ManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<VersionReleased> VersionReleaseds
        {
            get
            {
                if ((_VersionReleaseds == null))
                {
                    _VersionReleaseds = base.CreateObjectSet<VersionReleased>("VersionReleaseds");
                }
                return _VersionReleaseds;
            }
        }
        private ObjectSet<VersionReleased> _VersionReleaseds;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the VersionReleaseds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToVersionReleaseds(VersionReleased versionReleased)
        {
            base.AddObject("VersionReleaseds", versionReleased);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model", Name="VersionReleased")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class VersionReleased : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new VersionReleased object.
        /// </summary>
        /// <param name="versionID">Initial value of the VersionID property.</param>
        /// <param name="versionNumber">Initial value of the VersionNumber property.</param>
        public static VersionReleased CreateVersionReleased(global::System.Int32 versionID, global::System.String versionNumber)
        {
            VersionReleased versionReleased = new VersionReleased();
            versionReleased.VersionID = versionID;
            versionReleased.VersionNumber = versionNumber;
            return versionReleased;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 VersionID
        {
            get
            {
                return _VersionID;
            }
            set
            {
                if (_VersionID != value)
                {
                    OnVersionIDChanging(value);
                    ReportPropertyChanging("VersionID");
                    _VersionID = StructuralObject.SetValidValue(value, "VersionID");
                    ReportPropertyChanged("VersionID");
                    OnVersionIDChanged();
                }
            }
        }
        private global::System.Int32 _VersionID;
        partial void OnVersionIDChanging(global::System.Int32 value);
        partial void OnVersionIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VersionNumber
        {
            get
            {
                return _VersionNumber;
            }
            set
            {
                OnVersionNumberChanging(value);
                ReportPropertyChanging("VersionNumber");
                _VersionNumber = StructuralObject.SetValidValue(value, false, "VersionNumber");
                ReportPropertyChanged("VersionNumber");
                OnVersionNumberChanged();
            }
        }
        private global::System.String _VersionNumber;
        partial void OnVersionNumberChanging(global::System.String value);
        partial void OnVersionNumberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Release
        {
            get
            {
                return _Release;
            }
            set
            {
                OnReleaseChanging(value);
                ReportPropertyChanging("Release");
                _Release = StructuralObject.SetValidValue(value, "Release");
                ReportPropertyChanged("Release");
                OnReleaseChanged();
            }
        }
        private Nullable<global::System.DateTime> _Release;
        partial void OnReleaseChanging(Nullable<global::System.DateTime> value);
        partial void OnReleaseChanged();

        #endregion

    }

    #endregion

}
